# Context Property
When you are making a QML project, once you want to make use of C++ back-end along with the QML frontend, one way to do so is by using ContextProperty

:toc:
:sectnums:

== Introduction
When you are making a Qt project using QML for the front-end of the application instead of QWidget, you will then be able to declare some user interfaces, although, these interfaces won't communicate with the back-end (C++) part of the application by theirselves.

Even though these communication can be a real plus to your application, to fetch / update or even create data. There are several ways to do so.

== Context Property
A way for you to do so, is by using the `ContextProperty` of your application.

NOTE: A `ContextProperty` is an object that holds the objects identified by _id_ in a _QML_ document. You can then use the methods named `nameForObject()` as well as `objectForName()` to retrieve them on the C++ side.

=== nameForObject method
This method came from the `QQMLContext` class and returns the name of _object_ in this context, or an empty string if _object_ isn't named in the context. Objects are named by the method named `setContextProperty`, or as properties of a context object, or by ids in the case of QML created context.

==== setContextProperty
This method sets the value of the _name_ property on the specific context:

```cpp
void QQmlContext::setContextProperty(const QString &name, QObject *value)
```

=== objectForNamed method
This method returns the object for a given _name_ in this context. Returns nullptr if _name_ is not available in the context or if the value assoiated with _name_ isn't a `QObject`. 

Objects are then named by the method `setContextProperty()`, or as properties of a context object, or by ids in the case of QML created context. In contrast to `contextProperty()`, this method does not traverse the context hierarchy. If the name is not found in the current context, nullptr is returned.

==== The context
Contexts also allow data to be exposed to the QML components instantiated by the QML engine. Such data is invisible to any tooling, including the link:https://doc.qt.io/qt-6/qtqml-qtquick-compiler-tech.html[Qt Quick Compiler] and to future readers of the QML documents in question. It will only be exposed if the QML component is instantiated in the specific c++ context you are envisioning. In other places, different context data may be exposed instead.

Instead of using the QML context to expose data to your QML components, you should either create additional object properties to hold the data of use link:https://doc.qt.io/qt-6/qqmlintegration-h.html#QML_SINGLETON[singletons]. See link:https://doc.qt.io/qt-6/qtqml-cppintegration-exposecppstate.html[exposing C++ state to QML].

== Using Context property
When you want to make use of the context property, you will first need to design your class.

IMPORTANT: This class has to inherit from QObject to be recognized by the `rootContext` and then also having the `Q_OBJECT` macro on it.

Then here is an example:

```cpp
#include <QObject>
#include <QString>

class CppWorker : public QObject {
    Q_OBJECT
public:
    explicit CppWorker(QObject *po_object = nullptr);

    // Q_INVOKABLE
    Q_INVOKABLE void regularMethod();
    Q_INVOKABLE QString regularMethodWithReturn(const QString &name, int age);

public slots:
    void cppSlot();
};
```
=== Communicate QML and C++
QML can easily be extended with functionality defined in C++ code.

Due to the tight integration of the QML engine with the link:https://doc.qt.io/qt-6/metaobjects.html[Qt meta object system], any functionality that is appropriately exposed by a link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived class or a link:https://doc.qt.io/qt-6/qobject.html#Q_GADGET[QGadget] type is accessible from the QML code. This enables C++ data and functions to be accessible directly from QML, ofren with little or no modifications.

The QML engine has the ability to introspect link:https://doc.qt.io/qt-6/qobject.html[QObject] instances through the meta-object system. This means any QML code can access the following members of an instance of a link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived class:

* Properties `Q_PROPERTY`
* Methods (providing they are public slots or flagged with the link:https://doc.qt.io/qt-6/qobject.html#Q_INVOKABLE[Q_INVOKABLE] macro)
* Signals

==== Exposing properties
A _property_ can be specified for any link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived class using the link:https://doc.qt.io/qt-6/qobject.html#Q_PROPERTY[Q_PROPERTY]() macro. A property is a class data member with an associated read function and optional write function.

All properties of a link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived class or a link:https://doc.qt.io/qt-6/qobject.html#Q_GADGET[Q_GADGET] class are accessible from QML.

For example, below is a _Message_ class with an author property. As specified by the link:https://doc.qt.io/qt-6/qobject.html#Q_PROPERTY[Q_PROPERTY] macro call, this property is readable through the `author()` method, adn writable through the `setAuthor()` method:

NOTE: Do not use _typedef_ or using for link:https://doc.qt.io/qt-6/qobject.html#Q_PROPERTY[Q_PROPERTY] types as these will confuse moc. This may make certain type comparison fail.

So instead of:
```cpp
using FooEnum = Foo::Enum;

class Bar: public QObject {
    Q_OBJECT
    Q_PROPERTY(FooEnum enum READ enum WRITE setEnum NOTIFY enumChanged)
};
```

Refer to the type directly:

```cpp
class Bar : public QObject {
    Q_OBJECT
    Q_PROPERTY(Foo::Enum enum READ enum WRITE setEnum NOTIFY enumChanged)
};
```
In order to make *Message* available, you need to use link:https://doc.qt.io/qt-6/qqmlintegration-h.html#QML_ELEMENT[QML_ELEMENT] in C++ and link:https://doc.qt.io/qt-6/qt-add-qml-module.html[qt_add_qml_module] in CMake.

```cpp
class Message : public QObject {
    Q_OBJECT
    QML_ELEMENT
    Q_PROPERTY(QString author READ autor WRITE setAuthor NOTIFY authorChanged)
public:
    void setAuthor(const QString &o_author) {
        if (o_author != _author) {
            _author = o_author;
            emit authorChanged(_author);
        }
    }
    
    QString author() const {
        return _author;
    }
    
signals:
    void authorChanged(const QString &o_auhtor);
    
private:
    QString _author;
};
```
An instance of _Message_ can be passed as required property to a file called _MyItem.qml_ to make it available:

```cpp
int main(int argc, char *argv[]) {
    QGuiApplication app(argc, argv);
    
    QQuickView view;
    Message message;
    view.setInitialProperties({"msg", &message});
    view.setSource(QUrl::fromLocalFile("MyItem.qml"));
    view.show();
    
    return app.exec();
}
```
Then, the author property could be read from _MyItem.qml_:
```cpp
// MyItem.qml
import QtQuick

Text {
    required property Message msg
    
    width: 100; height: 50
    text: msg.author // invokes Message::author() method
    
    Component.onCompleted: {
        msg.author = "Jonah" // Invoke messsage.setAuthor()
    }
}
```
==== QML and C++ interoperabilities
For maximum interoperability with QML, _any_ property that is writable should have an associated *NOTIFY* signal that is emitted whenever the property value has changed. This allows the property to be used with link:https://doc.qt.io/qt-6/qtqml-syntax-propertybinding.html[property binding], which is an essential feature of QML that enforces relationships between properties by automatically updating a property whenever any of its dependencies change in value.

In the above example, the associated NOTIFY signal for the author property is `authorChanged`, as specified in the link:https://doc.qt.io/qt-6/qobject.html#Q_PROPERTY[Q_PROPERTY] macro call. This means that whenever the signal is emitted - as it is when the author changes in `Message::setAuthor()` - this notifies the QML engine that any binding involving the author property must be updated, and in turn, the engine will update te text property by calling `Message::author()` again.

If the author property was writable but did not have an associated `NOTIFY` signal, the _text_ value would be initialized with the initial value returned by `Message::author()`, but would not be updated with any later changes to this property. In addition, any attempts to bind to the property from QML will produce a runtime warning from the engine.

NOTE: It is recommended that the NOTIFY signal be named _<property>Changed_ where _<property>_ is the name of the property. The associated property change signal handler generated by the QML engine will always take the form on _<property>Changed_, regardless of the name of the related C++ signal, so it is recommended that the signal name follows this convention to avoid any confusions.

==== Notes on the use of Notify signals
To prevent loops or excessive evaluation, developers should ensure that the property change signal is only rmitted once the property value has actually changed. Also if a property or group of properties is infrequently used, it is permitted to use the same `NOTIFY` signal for several properties. This should be done with care ensuring that performance doesn't suffers.

The presence of a `NOTIFY` signal does incur a small overhead. There are cases where a property's value is set at object construction time, and does not subsequently change. The most common case of this is when a type used link:https://doc.qt.io/qt-6/qtqml-syntax-objectattributes.html#grouped-properties[grouped properties], and the grouped property object is allocated once, and only freed when the object is deleted. In these cases, the _CONSTANT_ attribute may be added to the property declaration instead of a _NOTIFY_ signal.

The _CONSTANT_ attribute should only be used for properties whose value is set, and finalized, only in the class constructor. All other properties that want to be used in bindings should have a _NOTIFY_ signal instead.

==== Properties with Object types
Object-type properties are accessible from QML providing that the object type has been appropriately link:https://doc.qt.io/qt-6/qtqml-cppintegration-definetypes.html#registering-c-types-with-the-qml-type-system[registered] from the QML type system.

For example, the _Message_ below type might have a body property of type _MessageBody_ pointers:

```cpp
class Message : public QObject /* For slot, signals and QML binding purposes */ {
    Q_OBJECT // For slot, signal, qml binding purposes
    Q_PROPERTY(MessageBody *body READ body WRITE setBody NOTIFY bodyChanged)

public:
    MessageBody *body() const;
    void setBody(MessageBody *body);
};

class MessageBody : public QObject {
    Q_OBJECT
    Q_PROPERTY(QString text READ text WRITE setText NOTIFY textChanged)
// ...
};
```
Let's suppose `Message` type was link:https://doc.qt.io/qt-6/qtqml-cppintegration-definetypes.html#registering-c-types-with-the-qml-type-system[registered] with the QML type system, allowing it to be used as an object type from QML code.
```json
Message {
    // ...
}
```
If the `MessageBody` type was also registered with the type system, it would be possible to assign _MessageBody_ to the _body_ property of a _Message_. All from within QML code:
```json
Message {
    body: MessageBody {
        text: "Hello World !"
    }
}
```
==== Properties with Object-List types
Properties containing lists of link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived types can also be exposed to QML. For this purpose, however, one should use link:https://doc.qt.io/qt-6/qqmllistproperty.html[QQmlListProperty] rather than something liks link:https://doc.qt.io/qt-6/qlist.html[QList]<T> as a property type. This is because QList<T> is not a QObject-derived type, and so cannot provide the necessary QML property characteristics through the Qt meta object system, such as signal notifications when a list gets modified.

For example, The `MessageBoard` class below has a messages property of type link:https://doc.qt.io/qt-6/qqmllistproperty.html[QQmlListProperty] that stores a list of message instances:
```cpp
class MessageBoard : public QObject {
    Q_OBJECT
    Q_PROPERTY(QQmlListProperty<Message> messages READ messages)
public:
    QQmlListProperty<Message> messages();
    
private:
    static void append_message(QQmlListProperty<Message> *list, Message *msg);
    
    QList<Message *> _o_messages;
}
```
Thie MessageBoard::messages() function simply creates and returns a link:https://doc.qt.io/qt-6/qqmllistproperty.html[QQmlListProperty] from it link:https://doc.qt.io/qt-6/qlist.html[QList]<T> m_message member, passing the appropriate list modification functions as required by the link:https://doc.qt.io/qt-6/qqmllistproperty.html[QQmlListProperty] constructor:

```cpp
QQmlListProperty<Message> MessageBoard::messages()
{
    return QQmlListProperty<Message>(this, 0, &MessageBoard::append_message);
}

void MessageBoard::append_message(QQmlListProperty<Message> *list, Message *msg)
{
    MessageBoard *msgBoard = qobject_cast<MessageBoard *>(list->object);
    if (msg)
        msgBoard->m_messages.append(msg);
}
```
Note that the template class type for the link:https://doc.qt.io/qt-6/qqmllistproperty.html[QQmlListProperty] in this case, Message must be link:https://doc.qt.io/qt-6/qtqml-cppintegration-definetypes.html#registering-c-types-with-the-qml-type-system[registered] with the QML type system.

==== Grouped property
Any read-only object-type property is accessible from QML code as a _grouped property_. This can be used to expose a group of related properties that describe a set of attributes for a type.

For example, suppose the `Message::author` property was of type `MessageAuthor` rather than a simple `string`, with `sub-properties` of a name and email like:

```cpp
class MessageAuthor : public QObject {
    Q_PROPERTY(QString name READ name WRITE setName)
    Q_PROPERTY(QString email READ email WRITE setEmail)
public:
    ...
};

class Message : public QObject {
    Q_OBJECT
    Q_PROPERTY(MessageAuthor* author READ author)
public:
    Message(QObject *parent)
        : QObject{ parent }, m_author(new MessageAuthor(this)) {}
    
    MessageAuthor *author() const {
        return m_author;
    }
private:
    MessageAuthor *m_author;
};
```
The _author_ property could be written to using the link:https://doc.qt.io/qt-6/qtqml-syntax-objectattributes.html#grouped-properties[grouped property syntax] in QML, like this:
```json
Message {
    author.name: "Alexandra"
    author.email: "alexandra@gmail.com"
}
```
A type that is exposed as a grouped property differs from an link:https://doc.qt.io/qt-6/qtqml-cppintegration-exposecppattributes.html#properties-with-object-types[object-type property] in that the grouped property is read-only, and is initialized to a valid value by the parent object at construction. The grouped property's sub-properties may be modified from QML, but the grouped property object itself will never change, whereas an object-type property may be assigned a new Object value from QML at any time. Thus the lifetime of a grouped property object is controlled strictly by the C++ parent implementation, whereas an object-type property can be freely created and destroyed through QML code.

==== Exposing Methods (Including Qt Slots)
Any method of a link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived type is accessible from QML code if it is:

* A public method flagged with the link:https://doc.qt.io/qt-6/qobject.html#Q_INVOKABLE[Q_INVOKABLE] macro
* A method with a static Qt link:https://doc.qt.io/qt-6/signalsandslots.html[slot]

For example, the _MessageBoard_ class below has a _postMessage()_ method that has been flagged with the link:https://doc.qt.io/qt-6/qobject.html#Q_INVOKABLE[Q_INVOKABLE] macro, as well as a `refresh()` method that is a public slot like so:

```cpp
class MessageBoard : public QObject {
    Q_OBJECT
    QML_ELEMENT

public:
    Q_INVOKABLE bool postMessage(const QString &msg) {
        qDebug() << "Called the C++ method with: " << msg;
        return true;
    }

public slots:
    void refresh() {
        qDebug() << "Calling a C++ slot !";q
    }
};
```
If an instance of _MessageBoard_ was set as the required property for a file *MyItem.qml* could invoke the two methods as shown in the example below:

===== C++
```cpp
int main(int argc, char **argv) {
    QGuiApplication app(argc, argv);
    
    MessageBoard msgBoard;
    QQuickView view;
    view.setInitialProperties({"msgBoard", &msgBoard});
    view.setSource(QUrl::fromLocalFile("MyItem.qml"));
    view.show();
    
    return app.exec();
}
```

===== QML
```json
// MyItem.qml
import QtQuick 2.0

Item {
    required property MessageBoard msgBoard
    
    width: 100; height: 100
    
    MouseArea {
        anchors.fill : parent
        onClicked: {
            var result = msgBoard.postMessage("Hello from QML")
            console.log("Result of the post message: ", result)
            msgBoard.refresh()
        }
    }
}
```
If a C++ method has a parameter with a QObject* type, the parameter value can be passed from QML using an object id or a javaScript `var` value that references the object.

QML supports the calling of overloaded C++ functions. If there are multiple C++ functions with the same but different arguments, the correct function will be called accoridng to the number and the types of arguments that are provided.

Values returned from C++ methods are converted to JavaScript values when accessed from JavaScript expressions in QML.

==== C++ method and the 'this' object

You may want to retrieve a C++ method from one object and call it on a different object. Consider the following example, within a QML module called Example:

===== C++
```cpp
class Invokable : public Q_Object {
    Q_OBJECT
    QML_ELEMENT
public:
    Invokable(QObject *parent = nullptr) : QObject(parent) {}
    
    Q_INVOKABLE void invoke() { qDebug() << "Invoked on: " << objectName(); }
}
```
===== QML
```json
import QtQml
import Example

Invokable {
    objectName: "parent"
    property Invokable child : Invokable{}
    Component.onCompleted: child.invoke.call(this)
}
```

NOTE: If you load the QML code from a suitable main.cpp, it should print "Invoked on parent". However, due to a long standing bug, it doesn't. Historically, the 'this' object of C++-based method is inseparably bound to the method. CChanging this behavior for existing code would cause subtle errors since the 'this' object is implicit in many places. Since Qt 6.5 you can explicitly opt into the correct behavior and allow C++ method to accept a 'this' object. To do so, add the following pragme to your QML document:

```json
pragma NativeMethodBehavior: AcceptThisObject
```
In this line added, the example above will work as expected.

==== Exposing signals
Any public link:https://doc.qt.io/qt-6/signalsandslots.html[signal] of a link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived type is accessible from QML code.

The QML engine automatically creates a link:https://doc.qt.io/qt-6/qtqml-syntax-signals.html[signal handler] for any signal of a link:https://doc.qt.io/qt-6/qobject.html[QObject]-derived type that is used from QML. Signal handlers are always named _on<Signal>_ where _<Signal>_ is the name of the signal, with the first letter capitalized. All parameters passed by the signal are available in the signal handler through the parameter names.

For example, suppose the _MessageBoard_ class has a _newMessagePosted()_ signal with a single parameter, _subject_:

```cpp
class MessageBoard : public QObject {
    Q_OBJECT
public:
    // ...
signals:
    void newMessagePosted(const QString &subject);
}
```
If the *MessageBoard* type was link:https://doc.qt.io/qt-6/qtqml-cppintegration-definetypes.html#registering-c-types-with-the-qml-type-system[registered] with the QML type system, then a *MessageBoard* object declared in QML could receive the `newMessagePosted()` signal using a signal handler named `onNewMessagePosted` and examine the subject parameter value like so:

```json
MessageBoard {
    onNewMessagePosted: (subject) => console.log("New message received: ", subject)
}
```
As with property values and method parameters, a signal parameter must have a type that is supported by the QML engine; see link:https://doc.qt.io/qt-6/qtqml-cppintegration-data.html[Data Type Conversion Between QML and C++]. (Using an unregisterded type will not generate an error, but the parameter value will not be accessible from the handler itself).

Classes may have multiple signals with the same name, but only the final signal is accessible as a QML signal. Note that signals with the same name but different parameters cannot be distinguished frome one another.